# Site settings
title: Alaina N. Smith
subtitle: Oceanographer & Data Analyst | Data Visualizer | R Guru | Woodworker
email: anoelsm@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city: San Diego
state: CA
zip_code: 92102
country: United States of America
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/anoelsm
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/alaina-noel-smith/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/phytoplasmith

# Build settings
markdown: kramdown
