# Site settings
title: Alaina N. Smith
subtitle: Oceanographer | Data Scientist | R Guru
email: anoelsm@gmail.com
description: Alaina N. Smith, Ph.D.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city: San Diego
state: CA
zip_code: 92106
country: United States of America
phone: +1 571-425-0046

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/anoelsm
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/theofficialalainasmith
linkedin_url: https://www.linkedin.com/in/alaina-noel-smith/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/phytoplasmith
google_scholar_url: https://scholar.google.com/citations?user=0ez60bsAAAAJ&hl=en&authuser=1

# Build settings
markdown: kramdown
